image: node:8
stages:
- setup
- verify
yarn:
  stage: setup
  script:
  - npm install -g yarn
  - yarn --cache-folder=.yarn-cache
  cache:
    paths:
    - .yarn-cache/
    - node_modules/
lint:
  stage: verify
  cache:
    policy: pull
    paths:
    - node_modules/
  script:
  - node_modules/.bin/gulp lint
  - node_modules/.bin/gulp commitlint
test:
  stage: verify
  cache:
    policy: pull
    paths:
    - .yarn-cache/
  script:
  - npm install -g yarn
  - yarn --cache-folder=.yarn-cache
  - node_modules/.bin/gulp test!
  artifacts:
    paths:
    - coverage/
