image: node:10.14.2-stretch
stages: [ init, verify, deploy ]
.defs:
# only_code not used when an MR is created, hence the need for except_docs
- &only_code
  only:
    changes:
    - .gitlab-ci.yml
    - package.json
    - yarn.lock
    - '{gulpfile.js,packages,test}/**/*'
- &except_docs
  except:
  - /^docs\/./
- &cache_paths
  paths:
  - .cache/yarn
- &pull_cache
  cache:
    policy: pull
    <<: *cache_paths
- &yarn_install
  before_script:
  - yarn --cache-folder=.cache/yarn --pure-lockfile > /dev/null
yarn:
  stage: init
  <<: *except_docs
  <<: *only_code
  cache:
    <<: *cache_paths
  <<: *yarn_install
  script: $(npm bin)/antora version
lint:
  stage: verify
  <<: *except_docs
  <<: *only_code
  <<: *pull_cache
  <<: *yarn_install
  script: $(npm bin)/gulp lint
test:
  stage: verify
  <<: *except_docs
  <<: *only_code
  <<: *pull_cache
  <<: *yarn_install
  script: $(npm bin)/gulp test
  artifacts:
    paths:
    - coverage/
release:
  stage: deploy
  only:
  - releases@antora/antora
  environment: releases
  before_script:
  - yarn global add lerna@$(node -p 'require("./lerna.json").lerna') > /dev/null
  script:
  - scripts/release.sh
  - . releaserc
  - curl -o /dev/null -s -X POST -F "token=$CI_JOB_TOKEN" -F "ref=$RELEASE_BRANCH" -F "variables[ANTORA_VERSION]=$RELEASE_VERSION" https://gitlab.com/api/v4/projects/5565100/trigger/pipeline # triggers release of Docker image
