image: node:8
stages:
- setup
- verify
yarn:
  stage: setup
  script:
  - npm install -g yarn
  - yarn --cache-folder=.yarn-cache
  cache:
    paths:
    - node_modules/
    - packages/asciidoc-loader/node_modules/
    - packages/content-aggregator/node_modules/
    - packages/content-classifier/node_modules/
    - packages/document-converter/node_modules/
    - packages/navigation-builder/node_modules/
    - packages/playbook-builder/node_modules/
    - packages/ui-loader/node_modules/
    - .yarn-cache/
lint:
  stage: verify
  cache:
    policy: pull
    paths:
    - node_modules/
  script:
  - node_modules/.bin/gulp lint
  - node_modules/.bin/gulp commitlint
test:
  stage: verify
  cache:
    policy: pull
    paths:
    - node_modules/
    - packages/asciidoc-loader/node_modules/
    - packages/content-aggregator/node_modules/
    - packages/content-classifier/node_modules/
    - packages/document-converter/node_modules/
    - packages/navigation-builder/node_modules/
    - packages/playbook-builder/node_modules/
    - packages/ui-loader/node_modules/
  script: node_modules/.bin/gulp test!
  artifacts:
    paths:
    - coverage/
