image: node:8
stages:
- setup
- verify
yarn:
  stage: setup
  cache:
    paths:
    - .yarn-cache/
    - node_modules/
  script:
  - yarn --cache-folder=.yarn-cache
lint:
  stage: verify
  cache:
    policy: pull
    paths:
    - node_modules/
  script:
  - node_modules/.bin/gulp lint
  - node_modules/.bin/gulp commitlint
test:
  stage: verify
  cache:
    policy: pull
    paths:
    - .yarn-cache/
  script:
  - yarn --cache-folder=.yarn-cache
  # enable the next line to switch to a branch
  #- git checkout -B $CI_COMMIT_REF_NAME
  - node_modules/.bin/gulp test!
  artifacts:
    paths:
    - coverage/
