image: node:16-buster
stages: [init, verify, deploy]
variables:
  GIT_DEPTH: '5'
  npm_config_cache: &npm_cache_dir .cache/npm
  npm_config_fund: 'false'
  npm_config_prefer_offline: 'true'
.defs:
- &unless_docs_mr
  if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^docs\//
  when: never
- &if_code_pushed
  if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH !~ /^docs\//
  changes:
  - .eslintrc
  - .gitlab-ci.yml
  - .mocharc.js
  - package{-lock,}.json
  - 'packages/**/*'
- &if_schedule
  if: $CI_PIPELINE_SOURCE == "schedule"
- &if_releases
  if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_PATH == "antora/antora" && $CI_COMMIT_BRANCH == "releases"
  exists:
  - releaserc
- &npm_cache_config
  key: npm-cache
  paths:
  - *npm_cache_dir
- &npm_cache_pull_push
  cache:
    <<: *npm_cache_config
    policy: pull-push
- &npm_cache_pull
  cache:
    <<: *npm_cache_config
    policy: pull
- &npm_install
  before_script:
  - node -p '`Node.js ${process.version}`'
  - mv package.json package~.json && mv package-lock.json package-lock~.json
  - npm i --no-package-lock --no-save --no-audit --silent npm@$(node -p 'require("./package~.json").devDependencies.npm')
  - rm -f node_modules/.package-lock.json
  - mv package~.json package.json && mv package-lock~.json package-lock.json
  - npx npm i --quiet
- &save_coverage
  artifacts:
    paths:
    - coverage
# this step also seeds the dependency cache
lint:
  interruptible: true
  stage: init
  rules:
  - *unless_docs_mr
  - *if_code_pushed
  - *if_schedule
  <<: *npm_cache_pull_push
  <<: *npm_install
  script: npx npm run lint
test:node-12-linux:
  interruptible: true
  image: node:12-buster
  stage: verify
  rules:
  - *unless_docs_mr
  - *if_code_pushed
  - *if_schedule
  <<: *npm_cache_pull
  <<: *npm_install
  script: npx npm test
test:node-14-linux:
  interruptible: true
  image: node:14-buster
  stage: verify
  rules:
  - *if_schedule
  <<: *npm_cache_pull
  <<: *npm_install
  script: npx npm test
test:node-16-linux:
  interruptible: true
  stage: verify
  rules:
  - *unless_docs_mr
  - *if_code_pushed
  - *if_schedule
  <<: *npm_cache_pull
  <<: *npm_install
  script: npx npm run coverage
  <<: *save_coverage
test:node-17-linux:
  interruptible: true
  image: node:17-buster
  stage: verify
  rules:
  - *if_schedule
  <<: *npm_cache_pull
  <<: *npm_install
  script: npx npm test
test:macos:
  interruptible: true
  tags: [shared-macos-amd64]
  image: macos-11-xcode-12
  stage: verify
  rules:
  - *if_schedule
  <<: *npm_cache_pull
  <<: *npm_install
  script: npx npm test
# https://gitlab.com/gitlab-org/ci-cd/shared-runners/images/gcp/windows-containers/-/blob/main/cookbooks/preinstalled-software/README.md
test:windows:
  tags: [windows]
  stage: verify
  interruptible: true
  rules:
  - *unless_docs_mr
  - *if_code_pushed
  - *if_schedule
  # cache does not currently work on the Windows runner
  #<<: *npm_cache_pull
  before_script:
  - choco upgrade -y nodejs --version=12.22.7
  - node -p '`Node.js ${process.version}`'
  - Get-ChildItem package*.json | Rename-Item -NewName { $_.Name -replace '.json','~.json' }
  - npm i --no-package-lock --no-save --no-audit --silent npm@$(node -p "require('./package~.json').devDependencies.npm")
  - Get-ChildItem package*~.json | Rename-Item -NewName { $_.Name -replace '~.json','.json' }
  - if (Test-Path node_modules/.package-lock.json) { Remove-Item node_modules/.package-lock.json }
  - npx npm i --quiet
  script: npx npm run coverage
  <<: *save_coverage
release:
  stage: deploy
  environment: releases
  rules:
  - *if_releases
  before_script:
  - npm i -g --no-audit --silent lerna@$(node -p 'require("./lerna.json").lerna')
  script:
  - scripts/release.sh
  # triggers release of Docker image
  - env $(echo -en $(cat releaserc)) sh -c 'curl -o /dev/null -s -X POST -F "token=$CI_JOB_TOKEN" -F "ref=$RELEASE_BRANCH" -F "variables[ANTORA_VERSION]=$RELEASE_VERSION" $DOCKER_IMAGE_PIPELINE_TRIGGER'
