image: node:8
stages:
- setup
- verify
yarn:
  stage: setup
  cache:
    paths:
    - .yarn-cache/
  script:
  - yarn --cache-folder=.yarn-cache --no-progress --pure-lockfile
lint:
  stage: verify
  cache:
    policy: pull
    paths:
    - .yarn-cache/
  script:
  - yarn --cache-folder=.yarn-cache --no-progress --pure-lockfile
  - node_modules/.bin/gulp lint
  - node_modules/.bin/gulp commitlint
test:
  stage: verify
  cache:
    policy: pull
    paths:
    - .yarn-cache/
  script:
  # enable next line to guarantee we're on a branch
  #- git checkout -B $CI_COMMIT_REF_NAME
  - yarn --cache-folder=.yarn-cache --no-progress --pure-lockfile
  - node_modules/.bin/gulp test!
  artifacts:
    paths:
    - coverage/
